### PR TITLE
Fix setColor not resetting the effect

### PR DESCRIPTION
**Pull request by tamhuynhit**
The previous PR #3 that added setColor function don't work for me because they didn't reset the layout. So here is a small fix

Please review and let me know if there is any issue. Thanks

### CODE REVIEW

**Comment by tamhuynhit** [comment]
@booncol Are you still maintaining this project? I surely need this feature and really don't want to change to another library so far. Please support, thanks

**Comment by ghost** [comment]
@tamhuynhit  Could not resolve com.github.tamhuynhit:pulsator4droid:fix-set-color-reset-SNAPSHOT, getting this error. Is this not longer available ?

**Comment by tamhuynhit** [comment]
@snehabhegade Try this:
```
implementation 'com.github.tamhuynhit:Pulsator4Droid:fix-set-color-reset-SNAPSHOT'
```

**Comment by ghost** [comment]
> @snehabhegade Try this:
> 
> ```
> implementation 'com.github.tamhuynhit:Pulsator4Droid:fix-set-color-reset-SNAPSHOT'
> ```

This worked, did this change recently ? Didn't know it was case sensitive issue. 
Thanks alot :)

**Comment by tamhuynhit** [comment]
@snehabhegade Nah I changed nothing, the forked repo is always public.

I just generate the link from here: [jitpack.io](https://jitpack.io/#tamhuynhit/Pulsator4Droid/fix-set-color-reset-SNAPSHOT)

**Review by booncol — APPROVED** [review]

**Pull request merged**
